// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ExtendedModalController from "./extended_modal_controller.js"
application.register("extended-modal", ExtendedModalController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import NotificationController from "./notification_controller.js"
application.register("notification", NotificationController)

import { Dropdown } from "tailwindcss-stimulus-components"
application.register('dropdown', Dropdown)

import AccordionController from "./accordion_controller.js"
application.register("accordion", AccordionController)

import TrixYoutubePluginController from "./trix_youtube_plugin_controller.js"
application.register("trix-youtube-plugin", TrixYoutubePluginController)

import { Autocomplete } from 'stimulus-autocomplete'
application.register('autocomplete', Autocomplete)

import Carousel from "stimulus-carousel"
application.register("carousel", Carousel)

 