meta_product_name: "Reynaud Charpente"
meta_title: "Reynaud Charpente, la passion du bois depuis 3 générations"
meta_description: "Reynaud Charpente, le spécialiste de la maison ossature bois en Isère et Savoie!"
meta_image: "rc-banner01.png" # should exist in `app/assets/images/`
